MTDSA-11832 Create & amend Charitable Giving tax relief - controller
hmrc/individuals-reliefs-api pull request #200
Opened 2022-06-07 12:37 UTC by mattstephens-hmrc

2022-06-08 14:59 UTC, vfryer12 commented on app/v1/controllers/CreateAndAmendCharitableGivingController.scala
> +      case NinoFormatError | BadRequestError | TaxYearFormatError | RuleIncorrectOrEmptyBodyError | RuleTaxYearNotSupportedError |
RuleIncorrectOrEmptyBodyError needs to be custom because we have paths

2022-06-08 14:59 UTC, vfryer12 commented on app/v1/models/errors/mtdErrors.scala
> +      code = "RULE_GIFTS_NON_UK_INVESTMENTS_AMOUNT_WITHOUT_NAMES",
RULE_GIFTS_NON_UK_AMOUNT_WITHOUT_NAMES is the error mapped to this message, I can see it was that beforehand?

2022-06-08 14:59 UTC, vfryer12 commented on it/v1/endpoints/CreateAndAmendCharitableGivingControllerISpec.scala
> +          override val mtdTaxYear: String = "2019-20"
I'm not sure with the tax year provided, isn't the minimum tax year 2017-18 and anything before this year triggers INVALID_ACCOUNTING_PERIOD?

2022-06-08 15:03 UTC, vfryer12 reviewed
Should we be auditing at this stage? Wouldn't we usually wait until the TXM page has been  created and approved before implementing?

2022-06-09 10:50 UTC, Mbrookesy requested changes

2022-06-09 10:50 UTC, Mbrookesy commented on app/v1/controllers/CreateAndAmendCharitableGivingController.scala
> +                                                          auditService: AuditService,
This declaration isn't used

2022-06-09 10:50 UTC, Mbrookesy commented on app/v1/controllers/CreateAndAmendCharitableGivingController.scala
> +    EndpointLogContext(controllerName = "AmendCharitableGivingController", endpointName = "createAndAmendCharitableGivingReliefs")
controller name only mentions that it's an amend and not both a create and amend

2022-06-09 10:50 UTC, Mbrookesy commented on conf/v1.routes
> +# PUT        /charitable-giving/:nino/:taxYear                v1.controllers.CreateAndAmendCharitableGivingController.handleRequest(nino: String, taxYear: String)
Probably best to remove the commented code from the routes until we need to put them in

2022-06-09 10:50 UTC, Mbrookesy commented on app/v1/controllers/CreateAndAmendCharitableGivingController.scala
> +//    auditService.auditEvent(event)
Probably best to remove the commented code from the controller since it'll be awhile before we do audits

2022-06-09 10:50 UTC, Mbrookesy commented on it/v1/endpoints/CreateAndAmendCharitableGivingControllerISpec.scala
> +            DesStub.onError(DesStub.POST, desUri(desTaxYear), BAD_REQUEST, errorBody("INVALID_ACCOUNTING_PERIOD"))
The name of the test says that it is testing if the taxYear provided is before `2017-18` but the data provided doesn't include a taxYear which is before the minimum.

Instead it's using the des error to make the error which should have been covered in the later test for downstream service errors.

2022-06-09 10:50 UTC, Mbrookesy commented on test/v1/controllers/CreateAndAmendCharitableGivingControllerSpec.scala
> +    )
If the audits aren't being implemented then we don't need the tests for them

2022-06-09 12:54 UTC, Mbrookesy requested changes

2022-06-09 12:54 UTC, Mbrookesy commented on it/v1/endpoints/CreateAndAmendCharitableGivingControllerISpec.scala
> +
The test name doesn't match what is being tested.

The test should be testing that when the `taxYear` provided is before 2017-18 (e.g. 2016-17) then it should give the `RULE_TAX_YEAR_NOT_SUPPORTED` Error  with the des stub response not being altered

2022-06-10 08:01 UTC, merged